"""Platform app icon files: Android adaptive icon vector drawables and the Apple AppIcon.appiconset.

Android: background, foreground and monochrome layers on the 108 dp adaptive canvas. The 1024 icon
grid maps onto the visible 72 dp (offset 18 dp); the mountain bleeds to the canvas edge, and the flame
and rings stay inside the 66 dp safe zone. The monochrome layer is the standalone mark, glyph-sized.
Apple: one set for both targets: iOS single-size 1024 (any, dark, tinted) and the macOS sizes.
"""
import json
import os

from brand_geometry import (MARK_BASE_ROUND, MARK_BASE_Y, MARK_BOX, PALETTE, WAVE_RADII, WAVE_STROKE,
                            flame_paths, lit_face, mountain, wave_paths)

ANDROID_GROUND = 1280          # bottom of the 108 dp canvas in icon-grid units: (108 - 18) / (72 / 1024)
ICON_TO_DP = 72 / 1024
NS = ('xmlns:android="http://schemas.android.com/apk/res/android" '
      'xmlns:aapt="http://schemas.android.com/aapt"')
VECTOR_OPEN = (f'<vector {NS}\n    android:width="108dp" android:height="108dp"\n'
               '    android:viewportWidth="108" android:viewportHeight="108">\n')
HEADER = "<!-- Generated by hub tools/brand/build_brand_assets.py; edit the generator, not this file. -->\n"


def _argb(hex_rgb):
    return "#FF" + hex_rgb.lstrip("#").upper()


def _gradient(x1, y1, x2, y2, stops, attr="android:fillColor"):
    items = "".join(f'<item android:offset="{o}" android:color="{_argb(c)}"/>' for o, c in stops)
    return (f'<aapt:attr name="{attr}"><gradient android:type="linear" android:startX="{x1}" '
            f'android:startY="{y1}" android:endX="{x2}" android:endY="{y2}">{items}</gradient></aapt:attr>')


def _rings(color_inner, color_outer, radii=WAVE_RADII):
    out = ""
    for radius, color in zip(radii, (color_inner, color_outer)):
        for d in wave_paths(radius):
            out += (f'    <path android:strokeColor="{_argb(color)}" android:strokeWidth="{WAVE_STROKE}" '
                    f'android:strokeLineCap="round" android:pathData="{d}"/>\n')
    return out


def android_background():
    stops = [(0, PALETTE["dawn-top"]), (1, PALETTE["dawn-bottom"])]
    return (HEADER + VECTOR_OPEN + '  <path android:pathData="M0,0h108v108h-108z">'
            + _gradient(54, 0, 54, 108, stops) + "</path>\n</vector>\n")


def android_foreground():
    outer, core = flame_paths()
    peak = mountain(ANDROID_GROUND)
    flame_stops = [(0, PALETTE["brand-fire"]), (0.55, PALETTE["brand-flame"]), (1, PALETTE["flame-tip"])]
    return (HEADER + VECTOR_OPEN
            + f'  <group android:translateX="18" android:translateY="18" android:scaleX="{ICON_TO_DP}" '
              f'android:scaleY="{ICON_TO_DP}">\n'
            + f'    <path android:fillColor="{_argb(PALETTE["brand-ember"])}" android:pathData="{peak}"/>\n'
            + f'    <group>\n      <clip-path android:pathData="{peak}"/>\n'
              f'      <path android:fillColor="{_argb(PALETTE["mountain-lit"])}" '
              f'android:pathData="{lit_face(ANDROID_GROUND)}"/>\n    </group>\n'
            + f'    <path android:pathData="{outer}">{_gradient(512, 562, 512, 210, flame_stops)}</path>\n'
            + f'    <path android:fillColor="{_argb(PALETTE["flame-core"])}" android:pathData="{core}"/>\n'
            + _rings(PALETTE["brand-flame"], PALETTE["wave-outer"])
            + "  </group>\n</vector>\n")


def android_monochrome():
    """Glyph-sized standalone mark centered in the safe zone; Android tints it, only alpha counts."""
    bx, by, bw, bh = MARK_BOX
    s = 56 / bw
    tx, ty = 54 - (bx + bw / 2) * s, 54 - (by + bh / 2) * s
    outer, core = flame_paths()
    ink = "#000000"
    return (HEADER + VECTOR_OPEN
            + f'  <group android:translateX="{tx:.3f}" android:translateY="{ty:.3f}" '
              f'android:scaleX="{s:.5f}" android:scaleY="{s:.5f}">\n'
            + f'    <path android:fillColor="{_argb(ink)}" '
              f'android:pathData="{mountain(MARK_BASE_Y, MARK_BASE_ROUND)}"/>\n'
            + f'    <path android:fillColor="{_argb(ink)}" android:fillType="evenOdd" '
              f'android:pathData="{outer} {core}"/>\n'
            + _rings(ink, ink)
            + "  </group>\n</vector>\n")


ADAPTIVE = ('<?xml version="1.0" encoding="utf-8"?>\n' + HEADER
            + '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
            '    <background android:drawable="@drawable/ic_launcher_background"/>\n'
            '    <foreground android:drawable="@drawable/ic_launcher_foreground"/>\n'
            '    <monochrome android:drawable="@drawable/ic_launcher_monochrome"/>\n'
            '</adaptive-icon>\n')


def write_android(res_dir):
    """Write the adaptive icon into an Android res/ directory (minSdk 29, so no -v26 qualifier)."""
    files = {
        "drawable/ic_launcher_background.xml": android_background(),
        "drawable/ic_launcher_foreground.xml": android_foreground(),
        "drawable/ic_launcher_monochrome.xml": android_monochrome(),
        "mipmap-anydpi/ic_launcher.xml": ADAPTIVE,
        "mipmap-anydpi/ic_launcher_round.xml": ADAPTIVE,
    }
    for rel, text in files.items():
        path = os.path.join(res_dir, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text if text.startswith("<?xml") else '<?xml version="1.0" encoding="utf-8"?>\n' + text)
    return sorted(files)


# (point size, scale, use the compact mark) for the macOS entries of the set.
MAC_SIZES = [(16, 1, True), (16, 2, True), (32, 1, True), (32, 2, False), (128, 1, False), (128, 2, False),
             (256, 1, False), (256, 2, False), (512, 1, False), (512, 2, False)]


def mac_filename(pt, scale):
    return f"icon-mac-{pt}{'@2x' if scale == 2 else ''}.png"


def apple_contents():
    images = [{"filename": "icon-ios-1024.png", "idiom": "universal", "platform": "ios", "size": "1024x1024"}]
    for value in ("dark", "tinted"):
        images.append({"appearances": [{"appearance": "luminosity", "value": value}],
                       "filename": f"icon-ios-1024-{value}.png", "idiom": "universal", "platform": "ios",
                       "size": "1024x1024"})
    for pt, scale, _ in MAC_SIZES:
        images.append({"filename": mac_filename(pt, scale), "idiom": "mac", "scale": f"{scale}x",
                       "size": f"{pt}x{pt}"})
    return json.dumps({"images": images, "info": {"author": "xcode", "version": 1}}, indent=2) + "\n"
